name: vps

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run VPS
        run: curl -sSf https://sshx.io/get | sh -s run

      # Save files created/modified during the VPS session
      - name: Upload VPS data
        if: always()  # run even if the VPS step fails or is cancelled
        uses: actions/upload-artifact@v4
        with:
          name: vps-data
          path: |
            .               # everything in the workspace…
            !.git/          # …except the git metadata
            !**/node_modules/
            !**/.git/
